/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-May-2022 1:59:17 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

IF DB_ID('qlKH') IS NOT NULL
BEGIN
	DROP DATABASE qlKH
END

CREATE DATABASE qlKH
GO
USE qlKH
GO
/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_BangCap_GiaoVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [BangCap] DROP CONSTRAINT [FK_BangCap_GiaoVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_LichHoc_KhoaHoc]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ChiTietKH] DROP CONSTRAINT [FK_LichHoc_KhoaHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_GiaoVien_NguoiDung]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [GiaoVien] DROP CONSTRAINT [FK_GiaoVien_NguoiDung]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KhoaHoc_GiaoVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [KhoaHoc] DROP CONSTRAINT [FK_KhoaHoc_GiaoVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ThamGiaKH_KhoaHoc]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ThamGiaKH] DROP CONSTRAINT [FK_ThamGiaKH_KhoaHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ThamGiaKH_NguoiDung]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ThamGiaKH] DROP CONSTRAINT [FK_ThamGiaKH_NguoiDung]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ThongTinNganHang_NguoiDung]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ThongTinNganHang] DROP CONSTRAINT [FK_ThongTinNganHang_NguoiDung]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_YeuThich_KhoaHoc]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [YeuThich] DROP CONSTRAINT [FK_YeuThich_KhoaHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_YeuThich_NguoiDung]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [YeuThich] DROP CONSTRAINT [FK_YeuThich_NguoiDung]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[BangCap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [BangCap]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ChiTietKH]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ChiTietKH]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[GiaoVien]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [GiaoVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[KhoaHoc]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [KhoaHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NguoiDung]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NguoiDung]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ThamGiaKH]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ThamGiaKH]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ThongTinNganHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ThongTinNganHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[YeuThich]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [YeuThich]
GO

/* Create Tables */

CREATE TABLE [BangCap]
(
	[MaGV] varchar(10) NOT NULL,
	[STT] int NOT NULL,
	[TenBang] nvarchar(50) NULL,
	[NgayCap] date NULL,
	[NoiCap] nvarchar(50) NULL
)
GO

CREATE TABLE [ChiTietKH]
(
	[MaKH] varchar(10) NOT NULL,
	[STT] int NOT NULL,
	[DuongDan] ntext NULL,
	[MoTa] nvarchar(100) NULL
)
GO

CREATE TABLE [GiaoVien]
(
	[MaGV] varchar(10) NOT NULL,
	[DanhGiaGV] float NULL,
	[MaTK] varchar(10) NULL
)
GO

CREATE TABLE [KhoaHoc]
(
	[MaKH] varchar(10) NOT NULL,
	[TenKhoaHoc] nvarchar(50) NULL,
	[Lop] int NULL,
	[HocPhi] int NULL,
	[SoBuoiDuKien] int NULL,
	[SoHocSinhToiThieu] int NULL,
	[MaGV] varchar(10) NULL,
	[DanhGiaKH] float NULL
)
GO

CREATE TABLE [NguoiDung]
(
	[MaTK] varchar(10) NOT NULL,
	[TenDN] varchar(50) NULL,
	[MatKhauDN] varchar(50) NULL,
	[HoTen] nvarchar(50) NULL,
	[Email] varchar(20) NULL,
	[SDT] varchar(20) NULL,
	[NgaySinh] date NULL
)
GO

CREATE TABLE [ThamGiaKH]
(
	[MaKH] varchar(10) NOT NULL,
	[MaTK] varchar(10) NOT NULL,
	[NgayThamGia] date NOT NULL,
	[TinhTrangThanhToan] nvarchar(50) NULL,
	[DanhGia] float NULL
)
GO

CREATE TABLE [ThongTinNganHang]
(
	[MaTK] varchar(10) NOT NULL,
	[SoTaiKhoan] varchar(20) NOT NULL,
	[TenNganHang] nvarchar(50) NULL
)
GO

CREATE TABLE [YeuThich]
(
	[MaKH] varchar(10) NOT NULL,
	[MaTK] varchar(10) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [BangCap] 
 ADD CONSTRAINT [PK_BangCap]
	PRIMARY KEY CLUSTERED ([STT] ASC,[MaGV] ASC)
GO

ALTER TABLE [ChiTietKH] 
 ADD CONSTRAINT [PK_LichHoc]
	PRIMARY KEY CLUSTERED ([STT] ASC,[MaKH] ASC)
GO

ALTER TABLE [GiaoVien] 
 ADD CONSTRAINT [PK_GiaoVien]
	PRIMARY KEY CLUSTERED ([MaGV] ASC)
GO

ALTER TABLE [KhoaHoc] 
 ADD CONSTRAINT [PK_KhoaHoc]
	PRIMARY KEY CLUSTERED ([MaKH] ASC)
GO

ALTER TABLE [NguoiDung] 
 ADD CONSTRAINT [PK_MaTK]
	PRIMARY KEY CLUSTERED ([MaTK] ASC)
GO

ALTER TABLE [NguoiDung] 
 ADD CONSTRAINT [U_Username] UNIQUE NONCLUSTERED ([TenDN] ASC)
GO

ALTER TABLE [ThamGiaKH] 
 ADD CONSTRAINT [PK_ThamGiaKH]
	PRIMARY KEY CLUSTERED ([MaKH] ASC,[MaTK] ASC,[NgayThamGia] ASC)
GO

ALTER TABLE [ThongTinNganHang] 
 ADD CONSTRAINT [PK_Table1]
	PRIMARY KEY CLUSTERED ([SoTaiKhoan] ASC,[MaTK] ASC)
GO

ALTER TABLE [YeuThich] 
 ADD CONSTRAINT [PK_YeuThich]
	PRIMARY KEY CLUSTERED ([MaKH] ASC,[MaTK] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [BangCap] ADD CONSTRAINT [FK_BangCap_GiaoVien]
	FOREIGN KEY ([MaGV]) REFERENCES [GiaoVien] ([MaGV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietKH] ADD CONSTRAINT [FK_LichHoc_KhoaHoc]
	FOREIGN KEY ([MaKH]) REFERENCES [KhoaHoc] ([MaKH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [GiaoVien] ADD CONSTRAINT [FK_GiaoVien_NguoiDung]
	FOREIGN KEY ([MaTK]) REFERENCES [NguoiDung] ([MaTK]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KhoaHoc] ADD CONSTRAINT [FK_KhoaHoc_GiaoVien]
	FOREIGN KEY ([MaGV]) REFERENCES [GiaoVien] ([MaGV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ThamGiaKH] ADD CONSTRAINT [FK_ThamGiaKH_KhoaHoc]
	FOREIGN KEY ([MaKH]) REFERENCES [KhoaHoc] ([MaKH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ThamGiaKH] ADD CONSTRAINT [FK_ThamGiaKH_NguoiDung]
	FOREIGN KEY ([MaTK]) REFERENCES [NguoiDung] ([MaTK]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ThongTinNganHang] ADD CONSTRAINT [FK_ThongTinNganHang_NguoiDung]
	FOREIGN KEY ([MaTK]) REFERENCES [NguoiDung] ([MaTK]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [YeuThich] ADD CONSTRAINT [FK_YeuThich_KhoaHoc]
	FOREIGN KEY ([MaKH]) REFERENCES [KhoaHoc] ([MaKH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [YeuThich] ADD CONSTRAINT [FK_YeuThich_NguoiDung]
	FOREIGN KEY ([MaTK]) REFERENCES [NguoiDung] ([MaTK]) ON DELETE No Action ON UPDATE No Action
GO
